      PROGRAM DRU850
C
C        MAY       1998   GLAHN   TDL   MOS-2000
C        JUNE      1998   GLAHN   ADDED MDATE( )
C        NOVEMBER  1998   GLAHN   REMOVED LKHERE( )
C        OCTOBER   1999   GLAHN   ND5 MADE GE ND12
C        MAY       2000   GLAHN   CHANGED DEFINITION OF ND4X1 TO 
C                                 INCLUDE ND2
C        MAY       2000   GLAHN   CHANGED MSTORE(7, ) TO (8, );
C                                 CHANGED ND4X1 TO ND4X1X2
C
C        PURPOSE
C           DRIVER FOR PROGRAM U850.  SEE U850 COMMENTS OR PROGRAM
C           WRITEUP FOR VARIABLE DEFINITIONS.  AN ATTEMPT HAS BEEN
C           MADE TO INCLUDE ALL INFORMATION IN THIS DRIVER THAT
C           THE USER OF U850 MIGHT HAVE TO CHANGE.
C
C        DATA SET USE
C            KFILDI    - UNIT NUMBER OF DEFAULT INPUT FILE.
C                        THIS IS PROBABLY SPECIFIED FOR THE SYSTEM
C                        BEING USED.  SET IN DATA STATEMENT.
C            KFILDO    - UNIT NUMBER OF DEFAULT OUTPUT (PRINT) FILE.
C                        THIS IS PROBABLY SPECIFIED FOR THE SYSTEM
C                        BEING USED.  SET IN DATA STATEMENT.
C
C        LET ND1  = THE MAXIMUM NUMBER OF STATIONS THAT CAN BE DEALT 
C                   WITH.  THIS DOES NOT HAVE TO BE LARGE ENOUGH TO 
C                   HOLD ALL THE STATIONS ON THE INPUT FILES.
C            ND2  = THE MAXIMUM NUMBER OF PROJECTIONS THAT CAN BE
C                   DEALT WITH.
C            ND4  = MAXIMUM NUMBER OF VARIABLES THAT CAN BE DEALT
C                   WITH.  THIS INCLUDES THE THREE TYPES,
C                   FORECASTS, OBSERVATION, AND MATCHING, BUT NOT
C                   PROJECTIONS OR SCORE GROUPS.
C            ND5  = THE MAXIMUM NUMBER OF STATION CALL LETTERS ON
C                   THE INPUT FILES.
C                   MUST BE GE THE LARGEST RECORD ON THE INPUT 
C                   INTERPOLATED FILE(S).  IT IS POSSIBLE THAT IT MUST
C                   BE AS LARGE AS THE PHYSICAL RECORD SIZE OF RECORDS
C                   ON THE INTERNAL STORAGE SYSTEM (NBLOCK) OR THE
C                   EXTERNAL FILE SYSTEM.  MUST ALSO BE GE ND1 AND
C                   FOR SAFETY SHOULD BE GE ND12.  (THIS LATTER IS
C                   ONLY FOR GFETCH, AND ND5 GE ND12 WOULD BE REQUIRED
C                   ONLY WHEN ACCUMULANTS ARE PACKED, WHICH THEY
C                   AREN'T.  HOWEVER, ND5 LT ND12 MIGHT MASK ANOTHER
C                   PROBLEM WHEN A PROBLEM IS BEING DIAGNOSED.)
C            ND6  = MAXIMUM NUMBER OF INPUT DATA SETS (MODELS) THAT 
C                   CAN BE DEALT WITH.  INCLUDED BOTH PREDICTORS
C                   AND PREDICTANDS.
C            ND7  = DIMENSION OF IS0( ), IS1( ), IS2( ), AND IS4( ).
C                   NOT ALL LOCATIONS ARE USED.  MAXIMUM SIZE IS FOR
C                   IS1( ) = 22 PLUS 32 CHARACTERS (ONE CHARACTER PER
C                   WORD) OF PLAIN TEXT = 54.  SET BY PARAMETER.
C            ND8  = MAXIMUM NUMBER OF DATES THAT CAN BE DEALT WITH.
C            ND9  = MAXIMUM NUMBER OF FIELDS STORED IN LSTORE( , )
C                   AND MSTORE( , ).  SECOND DIMENSION OF LSTORE( , ) 
C                   AND MSTORE( , ).
C            ND10 = THE MEMORY IN WORDS ALLOCATED TO THE SAVING OF 
C                   PACKED DATA IN CORE( ).  WHEN THIS
C                   SPACE IS EXHAUSTED, SCRATCH DISK WILL BE USED.
C            ND11 = MAXIMUM NUMBER OF SCORE GROUPS.  (INPUT)
C            ND12 = SIZE OF THE AREA TO HOLD ACCUMULANTS FOR A
C                   SCORE GROUP.
C            ND13 = MAXIMUM NUMBER OF SCORE NUMBERS TO OUTPUT FOR
C                   EACH OF THE SCORE GROUPS AND OUTPUT PACKAGES.
C        THEN IT IS SUFFICIENT THAT THE DIMENSIONS OF VARIABLES BE
C        AS INDICATED BELOW IN THIS EXAMPLE DIRVER.  NOTE THAT THE
C        VARIABLE L3264B IS SET TO 32 FOR A 32-BIT MACHINE AND TO
C        64 FOR A 64-BIT MACHINE.  L3264W AND NBLOCK WILL
C        AUTOMATICALLY ADJUST ACCORDINGLY.  ND5 SHOULD BE GE ND1.
C
      PARAMETER (L3264B=32)
      PARAMETER (L3264W=64/L3264B)
      PARAMETER (NBLOCK=6400/L3264B)
C     PARAMETER (ND1=MAX(NBLOCK,360))
      PARAMETER (ND1=5000)
C        WHEN DATA ARE IN MOS-2000 STORAGE AND ON DISK, A
C        DIAGNOSTIC WILL BE PRODUCED WHEN ND1.LT.NBLOCK.
      PARAMETER (ND2=150)
      PARAMETER (ND4=50)
      PARAMETER (ND4X1X2=ND4*ND1*ND2)
      PARAMETER (ND6=100)
      PARAMETER (ND7=54)
      PARAMETER (ND8=2000)
      PARAMETER (ND9=500000)
      PARAMETER (ND10=50000)
      PARAMETER (ND11=300)
      PARAMETER (ND4_ND11_3=ND4*ND11*3)
      PARAMETER (ND4_ND11_3_ND2=ND4*ND11*3*ND2)
      PARAMETER (ND12=50000000)
      PARAMETER (ND5=MAX(ND1,ND12))
C        ND5 MUST BE GE ND1.  ALSO FOR SAFETY, ND5 SHOULD
C        BE GE ND12
      PARAMETER (ND12X=((ND12+NBLOCK-1)/NBLOCK)*NBLOCK)
C        ND12X IS MADE AN EVEN MULTIPLE OF NBLOCK FOR RDDISK.
C        ND12X IS FURNISHED TO U850.
      PARAMETER (ND13=20)
C
      CHARACTER*1 CFMT(ND4,3,ND11),PREC(ND4,3,ND11)
      CHARACTER*1 HEAD(30,ND4,3,ND2,ND11)
      CHARACTER*2 WDTH(ND4)
      CHARACTER*8 CCALL(ND1,6)
      CHARACTER*8 CCALLD(ND5)
      CHARACTER*20 NAME(ND1)
      CHARACTER*30 GPNAME(ND1)
      CHARACTER*32 PLAIN(ND4,3,ND11)
      CHARACTER*60 NAMIN(ND6)
C
      DIMENSION ISDATA(ND1),SDATA(ND1),NGP(ND1),XDATA(ND1),
     2          MWORK(ND1)
      DIMENSION ID(4,ND4,3,ND2,ND11),IDPARS(15,ND4,3,ND2,ND11),
     1          JD(4,ND4,3,ND2,ND11),ITAU(ND4,3,ND2,ND11),
     2          NWHERE(ND4,3,ND2,ND11),
     3          TRESHL(ND4,3,ND11),TRESHU(ND4,3,ND11),
     4          JP(ND4,3,ND11),IWDTH(ND4,3,ND11),
     5          IPREC(ND4,3,ND11),
     6          NPROJ(ND11),NOCAT(3,ND11),
     7          NVRBL(3,ND11)
      DIMENSION IDC(4,ND4_ND11_3_ND2),ITAUC(ND4_ND11_3_ND2),
     1          JDC(4,ND4_ND11_3_ND2),IDPARC(15,ND4_ND11_3_ND2),
     2          NWHERC(ND4_ND11_3_ND2)
      DIMENSION IDSGP(ND11),IDSOUT(5,ND11),NOUT(ND11),
     1          IDSCOR(ND13,5,ND11),NSCOR(5,ND11)
      DIMENSION IPLAIN(L3264W,4,ND4,3,ND11)
      DIMENSION AA(ND4X1X2)
      DIMENSION IPACK(ND5),ICALLD(L3264W,ND5),
     1          IWORK(ND5),DATA(ND5)
      DIMENSION KFILIN(ND6),MODNUM(ND6),MSDATE(ND6),
     1          JFOPEN(ND6),MAXTAU(ND6),MDATE(ND6)
      DIMENSION INDEXC(ND1,ND6)
      DIMENSION IS0(ND7),IS1(ND7),IS2(ND7),IS4(ND7)
      DIMENSION IDATE(ND8),NWORK(ND8)
      DIMENSION LSTORE(12,ND9),MSTORE(8,ND9)
      DIMENSION CORE(ND10)
      DIMENSION ACC(ND12X),SCR(ND12X)
C
      EQUIVALENCE (PLAIN,IPLAIN)
      EQUIVALENCE (ICALLD,CCALLD)
C
      DATA KFILDI/5/,
     1     KFILDO/12/
      DATA NGP/ND1*0/
      DATA PLAIN/ND4_ND11_3*' '/ 
C
      CALL TIMPR(KFILDO,KFILDO,'START U850          ')
C
      CALL U850(KFILDI,KFILDO,CCALL,ISDATA,SDATA,
     1          NGP,GPNAME,XDATA,MWORK,NAME,ND1,
     2          ID,IDC,IDPARS,IDPARC,TRESHL,TRESHU,JD,JDC,
     3          JP,ITAU,ITAUC,NWHERE,NWHERC,IWDTH,WDTH,
     4          IPREC,PREC,CFMT,HEAD,IPLAIN,PLAIN,ND4,ND2,
     5          AA,ND4X1X2,
     6          NVRBL,NPROJ,NOCAT,
     7          IDSGP,IDSOUT,NOUT,IDSCOR,NSCOR,ND11,ND13,
     8          ICALLD,CCALLD,IPACK,DATA,IWORK,ND5,
     9          KFILIN,MODNUM,NAMIN,JFOPEN,MDATE,MAXTAU,
     A          MSDATE,INDEXC,ND6,
     B          IS0,IS1,IS2,IS4,ND7,
     C          IDATE,NWORK,ND8,
     D          LSTORE,MSTORE,ND9,
     E          CORE,ND10,NBLOCK,
     F          ACC,SCR,ND12X,L3264B,L3264W)
C
      CALL TIMPR(KFILDO,KFILDO,'END U850            ')
      STOP 850
      END
