      PROGRAM DRU600
C
C        FEBRUARY  1996   GLAHN   TDL   MOS-2000
C        DECEMBER  1996   GLAHN   MODIFIED FOR ICALLD.
C        JANUARY   1997   GLAHN   DIMENSION OF IPACK CHANGED.
C        JANUARY   1997   GLAHN   ELIMINATED SOME VARIABLES.
C        FEBRUARY  1997   GLAHN   ADDED JFOPEN( ).
C        JULY      1997   GLAHN   DIMENSIONS OF CCALL( ) CHANGED.
C        AUGUST    1997   GLAHN   CHANGED MSTORE(7, ) TO MSTORE(8, )
C        JUNE      1998   GLAHN   ADDED MDATE( )
C        NOVEMBER  1998   GLAHN   REMOVED LKHERE( )
C
C        PURPOSE
C           DRIVER FOR PROGRAM U600.  SEE U600 COMMENTS OR PROGRAM
C           WRITEUP FOR VARIABLE DEFINITIONS.  AN ATTEMPT HAS BEEN
C           MADE TO INCLUDE ALL INFORMATION IN THIS DRIVER THAT
C           THE USER OF U600 MIGHT HAVE TO CHANGE.
C
C        DATA SET USE
C            KFILDI    - UNIT NUMBER OF DEFAULT INPUT FILE.
C                        THIS IS PROBABLY SPECIFIED FOR THE SYSTEM
C                        BEING USED.  SET IN DATA STATEMENT.
C            KFILDO    - UNIT NUMBER OF DEFAULT OUTPUT (PRINT) FILE.
C                        THIS IS PROBABLY SPECIFIED FOR THE SYSTEM
C                        BEING USED.  SET IN DATA STATEMENT.
C
C        LET ND1  = THE MAXIMUM NUMBER OF STATIONS THAT CAN BE DEALT WITH
C                   IN THE REGRESSION ANALYSIS.  THIS DOES NOT HAVE
C                   TO BE LARGE ENOUGH TO HOLD ALL THE STATIONS ON
C                   THE INPUT FILES.
C            ND2  = THE SIZE OF Q( ).  SET BY PARAMETER.
C            ND4  = MAXIMUM NUMBER OF VARIABLES THAT CAN BE DEALT WITH 
C                   IN ONE RUN.  SECOND DIMENSION OF ID( , ), IDFORC( , )
C                   AND IDPARS( , ) AND DIMENSION OF TRESHL( ), TRESHU( ),
C                   NTYPVR( ), AND LIMIT( ).
C            ND5  = THE MAXIMUM NUMBER OF STATION CALL LETTERS ON
C                   THE INPUT FILES.  DIMENSION OF IWORK( ),
C                   DATA( ), IPACK( ), AND CCALLD( ).
C                   MUST BE GE THE LARGEST RECORD ON THE INPUT 
C                   INTERPOLATED FILE(S).  IT IS POSSIBLE THAT IT MUST
C                   BE AS LARGE AS THE PHYSICAL RECORD SIZE OF RECORDS
C                   ON THE INTERNAL STORAGE SYSTEM (NBLOCK) OR THE
C                   EXTERNAL FILE SYSTEM.  MUST ALSO BE GE ND1.
C            ND6  = MAXIMUM NUMBER OF INPUT DATA SETS (MODELS) THAT 
C                   CAN BE DEALT WITH.  INCLUDED BOTH PREDICTORS
C                   AND PREDICTANDS.
C            ND7  = DIMENSION OF IS0( ), IS1( ), IS2( ), AND IS4( ).
C                   NOT ALL LOCATIONS ARE USED.  MAXIMUM SIZE IS FOR
C                   IS1( ) = 22 PLUS 32 CHARACTERS (ONE CHARACTER PER
C                   WORD) OF PLAIN TEXT = 54.  SET BY PARAMETER.
C            ND8  = MAXIMUM NUMBER OF DATES THAT CAN BE DEALT WITH.
C            ND9  = MAXIMUM NUMBER OF FIELDS STORED IN LSTORE( , )
C                   AND MSTORE( , ).  SECOND DIMENSION OF LSTORE( , ) 
C                   AND MSTORE( , ).
C            ND10 = THE MEMORY IN WORDS ALLOCATED TO THE SAVING OF 
C                   PACKED DATA IN CORE( ).  WHEN THIS
C                   SPACE IS EXHAUSTED, SCRATCH DISK WILL BE USED.
C        THEN IT IS SUFFICIENT THAT THE DIMENSIONS OF VARIABLES BE
C        AS INDICATED BELOW IN THIS EXAMPLE DIRVER.  NOTE THAT THE
C        VARIABLE L3264B IS SET TO 32 FOR A 32-BIT MACHINE AND TO
C        64 FOR A 64-BIT MACHINE.  L3264W AND NBLOCK WILL
C        AUTOMATICALLY ADJUST ACCORDINGLY.  ND5 SHOULD BE GE ND1.
C
      PARAMETER (L3264B=32)
      PARAMETER (L3264W=64/L3264B)
      PARAMETER (NBLOCK=6400/L3264B)
      PARAMETER (ND1=MAX(NBLOCK,10000))
C        WHEN DATA ARE IN MOS-2000 STORAGE AND ON DISK, A
C        DIAGNOSTIC WILL BE PRODUCED WHEN ND1.LT.NBLOCK.
      PARAMETER (ND2=300000)
      PARAMETER (ND4=100)
      PARAMETER (ND4X1=ND4*ND1)
      PARAMETER (ND5=MAX(ND1,3000))
C        ND5 MUST BE GE ND1.
      PARAMETER (ND6=50)
      PARAMETER (ND7=54)
      PARAMETER (ND8=2000)
      PARAMETER (ND9=100000)
      PARAMETER (ND10=100000)
C
      CHARACTER*8 CCALL(ND1,6)
      CHARACTER*8 CCALLD(ND5)
      CHARACTER*20 NAME(ND1)
      CHARACTER*32 PLAIN(ND4)
      CHARACTER*60 NAMIN(ND6)
C
      REAL*8 Q(ND2)
      REAL*8 SUM(ND4),AVG(ND4),SIG(ND4),CONST(ND4),VH(ND4),A(ND4),
     1       ESS(ND4),RDVR(ND4),SRDVR(ND4),SESS(ND4),SA(ND4)
      REAL*8 P(ND4,ND4)
C
      DIMENSION ISDATA(ND1),SDATA(ND1),NGP(ND1),XDATA(ND1),
     2          MISING(ND1)
      DIMENSION ID(4,ND4),IDPARS(15,ND4),TRESHL(ND4),TRESHU(ND4),
     1          JD(4,ND4),JP(ND4),NTYPVR(ND4),ITAU(ND4),LIMIT(ND4),
     2          INDEX(ND4),JWORK(ND4),
     3          NWHERE(ND4),IDFORC(4,ND4),CORR(ND4),
     4          LP(5,ND4),SLP(5,ND4)
      DIMENSION AA(ND4X1),IA(ND4X1)
      DIMENSION IPACK(ND5),ICALLD(L3264W,ND5),
     1          IWORK(ND5),DATA(ND5)
      DIMENSION KFILIN(ND6),MODNUM(ND6),MSDATE(ND6),
     1          JFOPEN(ND6),MAXTAU(ND6),MDATE(ND6)
      DIMENSION INDEXC(ND1,ND6)
      DIMENSION IS0(ND7),IS1(ND7),IS2(ND7),IS4(ND7)
      DIMENSION IDATE(ND8),NWORK(ND8)
      DIMENSION LSTORE(12,ND9),MSTORE(8,ND9)
      DIMENSION CORE(ND10)
C
      EQUIVALENCE (ICALLD,CCALLD)
C
      DATA KFILDI/5/,
     1     KFILDO/12/
      DATA NGP/ND1*0/
      DATA PLAIN/ND4*' '/ 
      DATA NWHERE/ND4*0/
C
      CALL TIMPR(KFILDO,KFILDO,'START U600          ')
C
      CALL U600(KFILDI,KFILDO,
     1          CCALL,ISDATA,SDATA,NGP,XDATA,MISING,NAME,ND1,
     2          Q,ND2,
     3          ID,IDPARS,TRESHL,TRESHU,JD,INDEX,JP,
     4          NTYPVR,ITAU,LIMIT,JWORK,NWHERE,IDFORC,CORR,LP,SLP,
     5          SUM,AVG,SIG,CONST,VH,A,ESS,RDVR,SRDVR,SESS,SA,P,
     6          PLAIN,L3264B,L3264W,ND4,
     7          AA,IA,ND4X1,
     8          ICALLD,CCALLD,IPACK,DATA,IWORK,ND5,
     9          KFILIN,MODNUM,NAMIN,JFOPEN,MDATE,MAXTAU,
     A          MSDATE,INDEXC,ND6,
     B          IS0,IS1,IS2,IS4,ND7,
     C          IDATE,NWORK,ND8,
     D          LSTORE,MSTORE,ND9,
     E          CORE,ND10,NBLOCK)
C
      CALL TIMPR(KFILDO,KFILDO,'END U600            ')
      STOP 600
      END
