      PROGRAM DRU710
C
C        JUNE 1996   GLAHN   TDL   MOS-2000
C
C        PURPOSE
C           DRIVER FOR PROGRAM U710.  SEE U710 COMMENTS OR PROGRAM
C           WRITEUP FOR VARIABLE DEFINITIONS.  AN ATTEMPT HAS BEEN
C           MADE TO INCLUDE ALL INFORMATION IN THIS DRIVER THAT
C           THE USER OF U710 MIGHT HAVE TO CHANGE.
C
C        DATA SET USE
C            KFILDI    - UNIT NUMBER OF DEFAULT INPUT FILE.
C                        THIS IS PROBABLY SPECIFIED FOR THE SYSTEM
C                        BEING USED.  SET IN DATA STATEMENT.
C            KFILDO    - UNIT NUMBER OF DEFAULT OUTPUT (PRINT) FILE.
C                        THIS IS PROBABLY SPECIFIED FOR THE SYSTEM
C                        BEING USED.  SET IN DATA STATEMENT.
C
C        LET ND1  = THE MAXIMUM NUMBER OF STATIONS THAT CAN BE DEALT
C                   WITH.  THIS DOES NOT HAVE TO BE LARGE ENOUGH TO 
C                   HOLD ALL THE STATIONS ON THE INPUT FILES.
C            ND2  = MAXIMUM NUMBER OF VARIABLES TO BE DEALT WITH
C                   IN A SERIES.  THIS IS MAINLY FOR A GROUP OF
C                   PROBABILITY FORECASTS.
C            ND4  = MAXIMUM NUMBER OF VARIABLES THAT CAN BE DEALT WITH 
C                   IN ONE RUN.  SECOND DIMENSION OF ID( , ), IDFORC( , )
C                   AND IDPARS( , ) AND DIMENSION OF TRESHL( ), TRESHU( ),
C                   ITAU( ), AND LIMIT( ).
C            ND5  = THE MAXIMUM NUMBER OF STATION CALL LETTERS ON
C                   THE INPUT FILES.  DIMENSION OF IWORK( ),
C                   DATA( ), IPACK( ), AND CCALLD( ).
C                   MUST BE GE THE LARGEST RECORD ON THE INPUT 
C                   INTERPOLATED FILE(S).  IT IS POSSIBLE THAT IT MUST
C                   BE AS LARGE AS THE PHYSICAL RECORD SIZE OF RECORDS
C                   ON THE INTERNAL STORAGE SYSTEM (NBLOCK) OR THE
C                   EXTERNAL FILE SYSTEM.  MUST ALSO BE GE ND1.
C            ND6  = MAXIMUM NUMBER OF INPUT DATA SETS (MODELS) THAT 
C                   CAN BE DEALT WITH.  INCLUDED BOTH PREDICTORS
C                   AND PREDICTANDS.
C            ND7  = DIMENSION OF IS0( ), IS1( ), IS2( ), AND IS4( ).
C                   NOT ALL LOCATIONS ARE USED.  MAXIMUM SIZE IS FOR
C                   IS1( ) = 22 PLUS 32 CHARACTERS (ONE CHARACTER PER
C                   WORD) OF PLAIN TEXT = 54.  SET BY PARAMETER.
C            ND8  = MAXIMUM NUMBER OF DATES THAT CAN BE DEALT WITH.
C            ND9  = MAXIMUM NUMBER OF FIELDS STORED IN LSTORE( , )
C                   AND MSTORE( , ).  SECOND DIMENSION OF LSTORE( , ) 
C                   AND MSTORE( , ).
C            ND10 = THE MEMORY IN WORDS ALLOCATED TO THE SAVING OF 
C                   PACKED DATA IN CORE( ).  WHEN THIS
C                   SPACE IS EXHAUSTED, SCRATCH DISK WILL BE USED.
C        THEN IT IS SUFFICIENT THAT THE DIMENSIONS OF VARIABLES BE
C        AS INDICATED BELOW IN THIS EXAMPLE DIRVER.  NOTE THAT THE
C        VARIABLE L3264B IS SET TO 32 FOR A 32-BIT MACHINE AND TO
C        64 FOR A 64-BIT MACHINE.  L3264W AND NBLOCK WILL
C        AUTOMATICALLY ADJUST ACCORDINGLY.  ND5 SHOULD BE GE ND1.
C
      PARAMETER (L3264B=32)
      PARAMETER (L3264W=64/L3264B)
      PARAMETER (NBLOCK=6400/L3264B)
C     PARAMETER (ND1=MAX(NBLOCK,2000))
      PARAMETER (ND1=6000)
C        WHEN DATA ARE IN MOS-2000 STORAGE AND ON DISK, A
C        DIAGNOSTIC WILL BE PRODUCED WHEN ND1.LT.NBLOCK.
      PARAMETER (ND2=6)
      PARAMETER (ND4=20000)
      PARAMETER (ND4X1=ND4*ND1)
      PARAMETER (ND5=MAX(ND1,7000))
C        ND5 MUST BE GE ND1.
      PARAMETER (ND6=50)
      PARAMETER (ND7=54)
      PARAMETER (ND8=5000)
      PARAMETER (ND9=5000)
      PARAMETER (ND10=10000)
C
      CHARACTER*1 CFMT(ND4),PREC(ND4)
      CHARACTER*1 HEAD(30,ND4)
      CHARACTER*2 WDTH(ND4)
      CHARACTER*8 CCALL(ND1,6)
      CHARACTER*8 CCALLD(ND5)
      CHARACTER*20 NAME(ND1)
      CHARACTER*32 PLAIN(ND4)
      CHARACTER*60 NAMIN(ND6)
C
      DIMENSION ISDATA(ND1),SDATA(ND1),NGP(ND1),MWORK(ND1)
      DIMENSION XDATA(ND1,ND2)
      DIMENSION ID(4,ND4),IDPARS(15,ND4),TRESHL(ND4),TRESHU(ND4),
     1          JD(4,ND4),INDEX(ND4),JP(3,ND4),ITAU(ND4),NCAT(ND4),
     2          IWDTH(ND4),IPREC(ND4),NWHERE(ND4),ISCALD(ND4),
     3          PRINT(ND4)
      DIMENSION IPLAIN(L3264W,4,ND4)
      DIMENSION AA(ND4X1)
      DIMENSION IPACK(ND5),ICALLD(L3264W,ND5),
     1          IWORK(ND5),DATA(ND5)
      DIMENSION KFILIN(ND6),MODNUM(ND6),MSDATE(ND6),
     1          JFOPEN(ND6),MDATE(ND6),MAXTAU(ND6)
      DIMENSION INDEXC(ND1,ND6)
      DIMENSION IS0(ND7),IS1(ND7),IS2(ND7),IS4(ND7)
      DIMENSION IDATE(ND8),NWORK(ND8)
      DIMENSION LSTORE(12,ND9),MSTORE(8,ND9)
      DIMENSION CORE(ND10)
C
      EQUIVALENCE (PLAIN,IPLAIN)
      EQUIVALENCE (ICALLD,CCALLD)
C
      DATA KFILDI/5/,
     1     KFILDO/12/
      DATA NGP/ND1*0/
      DATA PLAIN/ND4*' '/ 
      DATA NWHERE/ND4*0/
C
      CALL TIMPR(KFILDO,KFILDO,'START U710          ')
C
      CALL U710(KFILDI,KFILDO,
     1          CCALL,ISDATA,SDATA,NGP,XDATA,MWORK,NAME,ND1,ND2,
     2          ID,IDPARS,TRESHL,TRESHU,JD,INDEX,JP,
     3          ITAU,IWDTH,WDTH,IPREC,PREC,CFMT,NWHERE,NCAT,
     4          ISCALD,PRINT,HEAD,IPLAIN,PLAIN,L3264B,L3264W,ND4,
     5          AA,ND4X1,
     6          ICALLD,CCALLD,IPACK,DATA,IWORK,ND5,
     7          KFILIN,MODNUM,NAMIN,JFOPEN,MDATE,MAXTAU,
     8          MSDATE,INDEXC,ND6,
     9          IS0,IS1,IS2,IS4,ND7,
     A          IDATE,NWORK,ND8,
     B          LSTORE,MSTORE,ND9,
     C          CORE,ND10,NBLOCK)
C
      CALL TIMPR(KFILDO,KFILDO,'END U710            ')
      STOP 710
      END
