      PROGRAM DRU700
C
C        FEBRUARY  1996   GLAHN   TDL   MOS-2000
C        JANUARY   1998   GLAHN   INSERTED JFOPEN,
C                                 2ND DIMENSION OF CALL( , )
C        AUGUST    1998   GLAHN   NTYPVR( ) CHANGED TO ITAU( );
C                                 ADDED MDATE( )
C        SEPTEMBER 1998   GLAHN   ADDED MAXTAU( ), MSTORE(7, ) CHANGED
C                                 TO MSTORE(8, )
C        SEPTEMBER 1998   GLAHN   DIMENSIONS OF PLAIN( , ) AND
C                                 ISCALD( , ) CHANGED
C        SEPTEMBER 1998   GLAHN   ADDED IDTPAR( ) AND IPLAIN( ),
C                                 REMOVED JP( ), JWORK( ), AND MISING( )
C        NOVEMBER  1998   GLAHN   REMOVED LKHERE( )
C        JANUARY   1999   GLAHN   UPDATED COMMENTS
C        FEBRUARY  1999   GLAHN   REDUCED IPACK(L3264W, ) TO IPACK( )
C        MAY       1999   GLAHN   ADDED ND3 TO DIMENSIONS OF ICAT( , )
C
C        PURPOSE
C           DRIVER FOR PROGRAM U700.  SEE U700 COMMENTS OR PROGRAM
C           WRITEUP FOR VARIABLE DEFINITIONS.  AN ATTEMPT HAS BEEN
C           MADE TO INCLUDE ALL INFORMATION IN THIS DRIVER THAT
C           THE USER OF U700 MIGHT HAVE TO CHANGE.
C
C        DATA SET USE
C            KFILDI    - UNIT NUMBER OF DEFAULT INPUT FILE.
C                        THIS IS PROBABLY SPECIFIED FOR THE SYSTEM
C                        BEING USED.  SET IN DATA STATEMENT.
C            KFILDO    - UNIT NUMBER OF DEFAULT OUTPUT (PRINT) FILE.
C                        THIS IS PROBABLY SPECIFIED FOR THE SYSTEM
C                        BEING USED.  SET IN DATA STATEMENT.
C
C        LET ND1  = MAXIMUM NUMBER OF STATIONS THAT CAN BE DEALT WITH.
C                   MUST ALSO BE GE BLOCK.
C            ND2  = MAXIMUM NUMBER OF TERMS PER EQUATION SET.
C            ND3  = MAXIMUM NUMBER OF PREDICTANDS IN AN EQUATION.
C            ND4  = MAXIMUM NUMBER OF VARIABLES THAT CAN BE DEALT WITH 
C                   IN ONE RUN.
C            ND5  = MAXIMUM NUMBER OF STATION CALL LETTERS ON
C                   THE INPUT FILES.  MUST BE GE THE LARGEST
C                   RECORD ON THE INPUT INTERPOLATED FILE(S).
C                   MUST ALSO BE GE ND1.
C            ND6  = MAXIMUM NUMBER OF INPUT DATA SETS (MODELS) THAT 
C                   CAN BE DEALT WITH.
C            ND7  = DIMENSION OF IS0( ), IS1( ), IS2( ), AND IS4( ).
C                   NOT ALL LOCATIONS ARE USED.  MAXIMUM SIZE IS FOR
C                   IS1( ) = 22 PLUS 32 CHARACTERS (ONE CHARACTER PER
C                   WORD) OF PLAIN TEXT = 54.
C            ND8  = MAXIMUM NUMBER OF DATES THAT CAN BE DEALT WITH.
C            ND9  = MAXIMUM NUMBER OF FIELDS STORED IN LSTORE( , )
C                   AND MSTORE( , ).
C            ND10 = THE MEMORY IN WORDS ALLOCATED TO THE SAVING OF 
C                   PACKED DATA IN CORE( ).  WHEN THIS SPACE IS
C                   EXHAUSTED, SCRATCH DISK WILL BE USED.
C            ND11 = MAXIMUM NUMBER OF SETS OF EQUATIONS, ONE SET
C                   PER INPUT FILE.
C            ND13 = MAXIMUM NUMBER OF DIFFERENT EQUATIONS PER SET.
C                   THIS WOULD BE = ND1 FOR SINGLE STATION EQUATIONS
C                   OR THE NUMBER OF REGIONS FOR REGIONAL EQUATIONS.
C        THEN IT IS SUFFICIENT THAT THE DIMENSIONS OF VARIABLES BE
C        AS INDICATED BELOW IN THIS EXAMPLE DIRVER.  NOTE THAT THE
C        VARIABLE L3264B IS SET TO 32 FOR A 32-BIT MACHINE AND TO
C        64 FOR A 64-BIT MACHINE.  L3264W AND NBLOCK WILL
C        AUTOMATICALLY ADJUST ACCORDINGLY.
C
      PARAMETER (L3264B=32)
      PARAMETER (L3264W=64/L3264B)
      PARAMETER (NBLOCK=6400/L3264B)
C     PARAMETER (ND1=MAX(NBLOCK,100))
      PARAMETER (ND1=5000)
      PARAMETER (ND2=20)
      PARAMETER (ND3=15)
      PARAMETER (ND4=10000)
      PARAMETER (ND5=MAX(ND1,2500))
      PARAMETER (ND6=200)
      PARAMETER (ND7=54)
      PARAMETER (ND8=2000)
      PARAMETER (ND9=50000)
      PARAMETER (ND10=1000)
      PARAMETER (ND11=100)
      PARAMETER (ND13=5000)
      PARAMETER (ND311=ND3*ND11)
C
      CHARACTER*8 CCALL(ND1,6),
     1            CCALLD(ND5)
      CHARACTER*20 NAME(ND1)
      CHARACTER*32 PLAIN(ND3,ND11)
      CHARACTER*60 NAMIN(ND6),EQNNAM(ND11)
C
      DIMENSION ISDATA(ND1),SDATA(ND1),XDATA(ND1)
      DIMENSION ID(4,ND4),IDPARS(15,ND4),TRESHL(ND4),
     1          JD(4,ND4),ITAU(ND4),INDEX(ND4),
     2          NWHERE(ND4),IDORD1(3,ND4),IDORD2(3,ND4)
      DIMENSION IPACK(ND5),ICALLD(L3264W,ND5),
     1          IWORK(ND5),DATA(ND5)
      DIMENSION KFILIN(ND6),MODNUM(ND6),MSDATE(ND6),
     1          JFOPEN(ND6),MDATE(ND6),MAXTAU(ND6)
      DIMENSION INDEXC(ND1,ND6)
      DIMENSION IS0(ND7),IS1(ND7),IS2(ND7),IS4(ND7)
      DIMENSION IDATE(ND8),NWORK(ND8)
      DIMENSION LSTORE(12,ND9),MSTORE(8,ND9)
      DIMENSION CORE(ND10)
      DIMENSION KFILEQ(ND11),KGP(ND11),MTANDS(ND11),ICAT(ND3,ND11)
      DIMENSION NGP(ND13,ND11),LGP(ND13,ND11),MTRMS(ND13,ND11)
      DIMENSION IDEQN(7,ND13,ND2,ND11)
      DIMENSION CONST(ND13,ND3,ND11),
     1          AVG(ND13,ND3,ND11),
     2          CORR(ND13,ND3,ND11)
      DIMENSION COEF(ND13,ND2,ND3,ND11)
      DIMENSION ISCALD(ND3,ND11)
      DIMENSION IDTAND(4,ND3,ND11),IDTPAR(15,ND3,ND11)
      DIMENSION IPLAIN(L3264W,4,ND3,ND11)
      DIMENSION LOCSTA(ND1,ND11)
      DIMENSION FCST(ND1,ND3,ND11)
C
      EQUIVALENCE (ICALLD,CCALLD)
      EQUIVALENCE (PLAIN,IPLAIN)
C
      DATA KFILDI/5/,
     1     KFILDO/12/
      DATA PLAIN/ND311*' '/ 
      DATA NWHERE/ND4*0/
C
      CALL TIMPR(KFILDO,KFILDO,'START U700          ')
C
      CALL U700(KFILDI,KFILDO,KFILEQ,EQNNAM,
     1          CCALL,ISDATA,SDATA,XDATA,NAME,ND1,
     2          ID,IDPARS,TRESHL,JD,INDEX,
     3          ITAU,NWHERE,IDORD1,IDORD2,
     4          ISCALD,IPLAIN,PLAIN,L3264B,L3264W,ND4,
     5          ICALLD,CCALLD,IPACK,DATA,IWORK,ND5,
     6          KFILIN,MODNUM,NAMIN,JFOPEN,MAXTAU,
     7          MSDATE,INDEXC,MDATE,ND6,
     8          IS0,IS1,IS2,IS4,ND7,
     9          IDATE,NWORK,ND8,
     A          LSTORE,MSTORE,ND9,
     B          IDEQN,CONST,AVG,CORR,COEF,IDTAND,IDTPAR,
     C          KGP,NGP,LGP,MTRMS,MTANDS,ICAT,LOCSTA,FCST,
     D          ND2,ND3,ND11,ND13,
     E          CORE,ND10,NBLOCK)
C
      CALL TIMPR(KFILDO,KFILDO,'END U700            ')
      STOP 700
      END
