      PROGRAM DRU625
C
C        NOVEMBER 1999   DREWRY   TDL   MOS-2000
C        JUNE     2000   GLAHN    ELIMINATED IDICT, INOAVG, IEOF
C        JULY     2000   GLAHN    MODIFIED EXTENSIVELY
C
C        PURPOSE
C           DRIVER FOR PROGRAM U625.  SEE U625 COMMENTS OR PROGRAM
C           WRITEUP FOR VARIABLE DEFINITIONS.  AN ATTEMPT HAS BEEN
C           MADE TO INCLUDE ALL INFORMATION IN THIS DRIVER THAT
C           THE USER OF U625 MIGHT HAVE TO CHANGE.  THE OPEN TO
C           THE CONTROL FILE 'U625.CN' IS HERE SO THAT ACCESS TO THE
C           CONTROL FILE CAN BE MODIFIED FOR CRAY OR BATCH HP JOBS.
C
C        DATA SET USE
C            KFILDI    - UNIT NUMBER OF DEFAULT INPUT FILE.
C                        THIS IS PROBABLY SPECIFIED FOR THE SYSTEM
C                        BEING USED.  SET IN DATA STATEMENT.
C            KFILDO    - UNIT NUMBER OF DEFAULT OUTPUT (PRINT) FILE.
C                        THIS IS PROBABLY SPECIFIED FOR THE SYSTEM
C                        BEING USED.  SET IN DATA STATEMENT.
C
C        LET ND1  = THE MAXIMUM NUMBER OF STATIONS THAT CAN BE DEALT WITH.
C            ND2  = MAXIMUM NUMBER OF TERMS IN ANY EQUATION.
C            ND3  = MAXIMUM NUMBER OF PREDICTANDS IN ANY EQUATION.
C            ND4  = MAXIMUM NUMBER OF DIFFERENT PREDICTORS IN RUN.
C            ND11 = MAXIMUM NUMBER OF EQUATION FILES.
C            ND13 = MAXIMUM NUMBER OF DIFFERENT EQUATIONS (REGIONS) 
C                   PER SET.
C        THEN IT IS SUFFICIENT THAT THE DIMENSIONS OF VARIABLES BE
C        AS INDICATED BELOW IN THIS EXAMPLE DIRVER.  NOTE THAT THE
C        VARIABLE L3264B IS SET TO 32 FOR A 32-BIT MACHINE AND TO
C        64 FOR A 64-BIT MACHINE.  L3264W WILL AUTOMATICALLY ADJUST 
C        ACCORDINGLY.
C
C         NONSYSTEM SUBROUTINES CALLED
C             TIMPR
C
      PARAMETER (L3264B=32,
     1           L3264W=64/L3264B,
     2 		 ND1=7100, 
     3           ND2=25, 
     4           ND3=15, 
     5           ND4=12000,
     6           ND11=260,
     7           ND13=ND1)
C      
      CHARACTER*8  CCALLEF, CCALLML, CDUPS, CMISS, CCALLD,
     1             ALSTAS, ALREGS, DSTAS
      CHARACTER*20 NAME, STNMEF
      CHARACTER*60 EQNNAM           
C
      DIMENSION CDUPS(ND1), CMISS(ND1), 
     1          IFOUND(ND1), CCALLD(ND1), LOCSTA(ND1), 
     2          IPACK(ND1), IWORK(ND1), SDATA(ND1), XDATA(ND1),
     3          ITIMEZ(ND1), NAME(ND1), NGPMSL(ND1),
     4          NGPRUN(ND1), ALSTAS(ND1), ALREGS(ND1),
     5          DSTAS(ND1), STNMEF(ND1)
      DIMENSION CCALLML(ND1,6), CCALLEF(ND1,6)
      DIMENSION IDTAND(4,ND3)
      DIMENSION ITAU(ND4), TRESHL(ND4)
      DIMENSION ID(4,ND4), IDPARS(15,ND4), JD(4,ND4)
      DIMENSION KFILEQ(ND11), EQNNAM(ND11), MODNUM(ND11), 
     1          JFOPEN(ND11)
      DIMENSION NGP(ND13), LGP(ND13), IRNGP(ND13), DNGP(ND13)
      DIMENSION CONST(ND13,ND3), AVG(ND13,ND3), CORR(ND13,ND3)
      DIMENSION MTRMS(ND13)
      DIMENSION COEF(ND13,ND2,ND3)
      DIMENSION IDEQN(7,ND13,ND2)  
C
      DATA KFILDI/5/,
     1     KFILDO/12/  
C
      CALL TIMPR(KFILDO,KFILDO,'START U625          ')
C
      CALL U625(KFILDI,KFILDO,KFILEQ,EQNNAM,MODNUM,JFOPEN, 
     1          CDUPS,CMISS,IFOUND,CCALLD,LOCSTA, 
     2          IPACK,IWORK,SDATA,XDATA,
     3          ITIMEZ,NAME,NGPMSL,
     4          NGPRUN,ALSTAS,ALREGS,
     5          DSTAS,STNMEF,ITAU,TRESHL,
     6          NGP,LGP,IRNGP,DNGP,
     7          CCALLML,CCALLEF,
     8          CONST,AVG,CORR,IDTAND,
     9          ID,IDPARS,JD,MTRMS,COEF,IDEQN,
     A          L3264B,L3264W,ND1,ND2,ND3,ND4,ND11,ND13)
C
      CALL TIMPR(KFILDO,KFILDO,'END U625            ')
C      
      STOP 625
      END      
